[package]
name = "folden"
version = "0.0.1"
authors = ["lambaaada <mayan.shoshani7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "folder_handler"
]

[dependencies]
folder_handler = {path = "folder_handler"}

clap = "2.33.3"
typetag = "0.1.6"
toml = "0.5.7"
serde = {version = "1.0.117", features = ["derive"] }