[package]
name = "folden"
version = "0.0.1"
authors = ["lambaaada <mayan.shoshani7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "folder_handler",
    "server"
]

[dependencies]
folder_handler = {path = "folder_handler"}
server = {path = "server"}

tonic = "0.3.1"
prost = "0.7"
prost-types = "0.7"
clap = "2.33.3"
typetag = "0.1.6"
toml = "0.5.7"
tokio = { version = "0.2"}
serde = {version = "1.0.117", features = ["derive"] }

[build-dependencies]
tonic-build = "0.3.1"