[package]
name = "folden"
version = "0.0.1"
authors = ["lambaaada <mayan.shoshani7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "generated_types",
    "workflows",
    "foldend"
]

[dependencies]
generated_types = {path = "generated_types"}
workflows = {path = "workflows"}
foldend = {path = "foldend"}

tonic = "0.3.1"
clap = "2.33.3"
typetag = "0.1.6"
dyn-clone = "1.0.4"
toml = "0.5.7"
futures = "0.3"
tokio = { version = "0.2", features = ["full"]}
serde = {version = "1.0.117", features = ["derive"] }

[package.metadata.deb]
section = "utility"
maintainer-scripts = "debian/"
systemd-units = { enable = false }
assets = [
    ["debian/foldend_config.toml", "/etc/foldend/foldend_config.toml", "644"],
    ["debian/foldend.service", "/lib/systemd/system/foldend.service", "644"],
    ["target/release/folden", "/usr/bin/", "755"],
    ["target/release/foldend", "/usr/sbin/", "755"]
]