#!/bin/sh
set -e

# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi

if [ "$1" = "purge" ] || [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge foldend.service >/dev/null || true
		deb-systemd-helper unmask foldend.service >/dev/null
	fi
fi

rm -rf /etc/foldend/