[package]
name = "generated_types"
version = "0.1.0"
authors = ["lambaaada <mayan.shoshani7@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.1"
prost = "0.6"
prost-types = "0.6"
tonic = "0.3.1"

[build-dependencies]
tonic-build = "0.3.1"